version: "3"
services:
  ropsten:
    image: ethereum/client-go:stable
    entrypoint: "geth --ropsten --http --http.corsdomain '*' --http.addr 0.0.0.0 --http.api admin,eth,debug,net,txpool,personal,web3 --syncmode 'light' --metrics"
    ports:
      - "30303:30303"
      - "8545:8545"
